<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>monksilly.ResourcefulHands</AssemblyName>
    <Product>Resourceful Hands</Product>
    <Version>0.10.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>14.0</LangVersion>
    <IsPackable>false</IsPackable>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>ResourcefulHands</RootNamespace>
    <WhiteKnuckleDir>Defined in ResourcefulHands.csproj.user!!</WhiteKnuckleDir> <!-- Ensure that this has BepInEx installed -->
    <CopyToBepInExPluginsDir>true</CopyToBepInExPluginsDir>
  </PropertyGroup>

  <Import Project="Properties/DeployToPlugins.targets" />
  <Import Project="UserConfig.props" Condition="Exists('UserConfig.props')" />

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.62" IncludeAssets="compile" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="rh_assets.bundle" />
    <None Remove="rh_assets.bundle" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ALINE">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/ALINE.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="andywiecko.BurstTriangulator">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/andywiecko.BurstTriangulator.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="AstarPathfindingProject">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/AstarPathfindingProject.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="BakeryRuntimeAssembly">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/BakeryRuntimeAssembly.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Bepinex\BepInEx.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="BepInEx.Harmony">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Bepinex\BepInEx.Harmony.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="BepInEx.Preloader">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Bepinex\BepInEx.Preloader.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Clipper2Lib">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Clipper2Lib.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Coffee.SoftMaskForUGUI">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Coffee.SoftMaskForUGUI.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Coffee.SoftMaskForUGUI.R">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Coffee.SoftMaskForUGUI.R.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="DarkMachineUI">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/DarkMachineUI.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="DOTween">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/DOTween.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Facepunch.Steamworks.Win64">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Facepunch.Steamworks.Win64.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Febucci.Attributes.Runtime">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Febucci.Attributes.Runtime.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Febucci.TextAnimator.Runtime">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Febucci.TextAnimator.Runtime.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Febucci.TextAnimator.TMP.Runtime">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Febucci.TextAnimator.TMP.Runtime.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="HarmonyXInterop">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Bepinex\HarmonyXInterop.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Mono.Cecil">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Bepinex\Mono.Cecil.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Mono.Cecil.Mdb">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Bepinex\Mono.Cecil.Mdb.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Mono.Cecil.Pdb">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Bepinex\Mono.Cecil.Pdb.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Mono.Cecil.Rocks">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Bepinex\Mono.Cecil.Rocks.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Bepinex\MonoMod.RuntimeDetour.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="MonoMod.Utils">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Bepinex\MonoMod.Utils.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="PackageTools">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/PackageTools.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Pathfinding.Ionic.Zip.Reduced">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Pathfinding.Ionic.Zip.Reduced.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="PrefabBaker">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/PrefabBaker.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="SeppePeelman.EditorTools.SurfaceAlignTool">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/SeppePeelman.EditorTools.SurfaceAlignTool.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Sirenix.OdinInspector.Attributes">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Sirenix.OdinInspector.Attributes.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Sirenix.Serialization.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Sirenix.Serialization.Config">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Sirenix.Serialization.Config.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Sirenix.Utilities">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Sirenix.Utilities.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Burst.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Burst.Unsafe">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Burst.Unsafe.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Collections.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Collections.LowLevel.ILSupport">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Collections.LowLevel.ILSupport.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Deformations">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Deformations.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Entities">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Entities.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Entities.Hybrid">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Entities.Hybrid.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Entities.Hybrid.HybridComponents">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Entities.Hybrid.HybridComponents.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Entities.UI">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Entities.UI.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.InputSystem.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.InputSystem.ForUI">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.InputSystem.ForUI.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.InputSystem.InGameHints">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.InputSystem.InGameHints.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.InputSystem.RebindingUI">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.InputSystem.RebindingUI.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.InternalAPIEngineBridge.002">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.InternalAPIEngineBridge.002.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Mathematics.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Mathematics.Extensions">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Mathematics.Extensions.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Mathematics.Extensions.Hybrid">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Mathematics.Extensions.Hybrid.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.MemoryProfiler">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.MemoryProfiler.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Postprocessing.Runtime">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Postprocessing.Runtime.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Profiling.Core">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Profiling.Core.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Scenes">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Scenes.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.ScriptableBuildPipeline">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.ScriptableBuildPipeline.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Serialization">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Serialization.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Timeline">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Timeline.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Transforms">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Transforms.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.Transforms.Hybrid">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.Transforms.Hybrid.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.VisualScripting.Antlr3.Runtime">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.VisualScripting.Antlr3.Runtime.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.VisualScripting.Core">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.VisualScripting.Core.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.VisualScripting.Flow">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.VisualScripting.Flow.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="Unity.VisualScripting.State">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/Unity.VisualScripting.State.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.AccessibilityModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.AccessibilityModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.AIModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.AIModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.AndroidJNIModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.AndroidJNIModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.AnimationModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.ARModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.ARModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.ClothModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.ClothModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.ClusterInputModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.ClusterInputModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.ClusterRendererModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.ClusterRendererModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.ContentLoadModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.ContentLoadModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.CrashReportingModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.CrashReportingModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.DirectorModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.DirectorModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.DSPGraphModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.DSPGraphModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.GameCenterModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.GameCenterModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.GIModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.GIModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.GridModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.GridModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.HotReloadModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.HotReloadModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.InputModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.JSONSerializeModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.LocalizationModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.LocalizationModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.NVIDIAModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.NVIDIAModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.ParticleSystemModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.PerformanceReportingModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.PerformanceReportingModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.Physics2DModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.ProfilerModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.ProfilerModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.PropertiesModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.PropertiesModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.ScreenCaptureModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.SharedInternalsModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.SharedInternalsModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.SpriteMaskModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.SpriteMaskModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.SpriteShapeModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.SpriteShapeModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.StreamingModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.StreamingModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.SubstanceModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.SubstanceModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.SubsystemsModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.SubsystemsModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.TerrainModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.TerrainPhysicsModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.TextCoreFontEngineModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.TextCoreFontEngineModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.TextCoreTextEngineModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.TextCoreTextEngineModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.TilemapModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.TLSModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.TLSModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UIElementsModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UmbraModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UmbraModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsCommonModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UnityAnalyticsModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UnityAnalyticsModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UnityConnectModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UnityConnectModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UnityCurlModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UnityCurlModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UnityTestProtocolModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UnityTestProtocolModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestWWWModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.VehiclesModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.VehiclesModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.VFXModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.VFXModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.VideoModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.VirtualTexturingModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.VirtualTexturingModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.VRModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.VRModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.WindModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.WindModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="UnityEngine.XRModule">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/UnityEngine.XRModule.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="WFowler1.BspImporter.Runtime">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/WFowler1.BspImporter.Runtime.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>
    <Reference Include="XNode">
      <HintPath>$(WhiteKnuckleDir)White Knuckle_Data/Managed/XNode.dll</HintPath>
      <Private>false</Private>
      <CopyLocal>false</CopyLocal>
    </Reference>

    <Publicize Include="Assembly-CSharp"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include=".github\ISSUE_TEMPLATE\bug_report.md" />
    <Content Include=".github\ISSUE_TEMPLATE\feature_request.md" />
  </ItemGroup>

</Project>
